[package]
name = "ratatui-rain"
version = "1.0.2"
edition = "2021"
license = "MIT"
description = "Roughly maintained fork of tui-rain"
homepage = "https://github.com/mafien0/ratatui-rain"
repository = "https://github.com/mafien0/ratatui-rain"
readme = "README.md"
keywords = ["tui", "ratatui", "rain"]

[dependencies]
rand = { version = "0.8.5", default-features = false }
rand_pcg = "0.3.1"
ratatui = { version = "0.30.1", default-features = false }

[dev-dependencies]
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.31"
ratatui = "0.30.1"
tokio = { version = "1.41.1", features = ["full"] }
